Support end date
apqlzm/medihunter pull request #6
Opened 2019-07-14 21:44 UTC by KrzysztofKarol

Support end date just by filtering results (AFAIK Medicover API doesn't support end date itself).

2019-07-24 16:08 UTC, apqlzm requested changes
Looks good although minor changes would make the code simpler and easier to read :wink:

2019-07-24 16:08 UTC, apqlzm commented on medicover_session.py
> +        if kwargs.get('end_date') is not None:
Maybe we could move code from the block to another method so it could look like this:
```python
if kwargs.get('end_date') is not None:
    appointmets = self.filter_out_late_appointments(appointments, end_date_str)
```

2019-07-24 16:08 UTC, apqlzm commented on medicover_session.py
> +                def parse_appointment_datetime_to_datetime(iso_date: str) -> datetime:
Inner functions could be replaced with well named variables, for instance instead of this
```python
def parse_appointment_datetime_to_datetime(iso_date: str) -> datetime:
    return datetime.strptime(iso_date, "%Y-%m-%dT%H:%M:%S")
```
we could have:

```python
appointment_datetime = datetime.strptime(iso_date, "%Y-%m-%dT%H:%M:%S")
```

2019-07-24 16:08 UTC, apqlzm commented on medicover_session.py
> +                def get_end_of_day(dt: datetime) -> datetime: return dt + timedelta(days=1, microseconds=-1)
instead of this:
```python
def get_end_of_day(dt: datetime) -> datetime: return dt + timedelta(days=1, microseconds=-1) 
```
we could have:
```python
end_date = dt + timedelta(days=1, microseconds=-1) 
```

2019-10-20 10:47 UTC, bnowakow commented
Wanted to code it myself before I checked pull requests. Works superbly. (: +1

2019-10-20 16:41 UTC, merged